= Teach spreadsheets

== About the project 

The aim of this project is to read teacher’s preferences to assign them to study groups in courses.This project is inspired by the link:https://github.com/oliviercailloux/Teach-spreadsheets[Teach-spreadsheets project].

Logos' Credits :

Icons made by link:https://www.flaticon.com/authors/freepik[Freepik] from link:https://www.flaticon.com/[www.flaticon.com]. +
Icons made by link:https://www.flaticon.com/authors/xnimrodx[nimrodx] from link:https://www.flaticon.com/[www.flaticon.com]. +
Icons made by link:https://www.flaticon.com/authors/freepik[Freepik] from link:https://www.flaticon.com/[www.flaticon.com]. +
Icons made by link:https://www.flaticon.com/authors/prosymbols[Prosymbols] from link:https://www.flaticon.com/[www.flaticon.com].

== Global idea of the project 

The main functionalities that this project will implement are described in the link:Doc\README.adoc#UseCaseDiag[use case diagram]. +
You can see how our program's gui looks like in link:Doc\README.adoc#GuiDescription[gui description]. +
The way we imagine the process of assignment is described in the link:Doc\README.adoc#SeqDiag[sequence diagram]. +
The classes implemented are described in the link:Doc\README.adoc#ClassDiag[class diagram].

== Fourth java iteration

* Group 1: SM/PO: Sarah

** Fixing as many issues as possible : Issues 22, 25, 32, 33 ... 
** Adding teacherAssignmentsToCourseAssignments() in CourseAssignment

* Group 2 : Hedi and Semida

** Fixing issue 34

** Making the project's main 


* Group 3 : Mike and Inès

** Completing the GUI for Assignment

