= Teach spreadsheets

== About the project 

The aim of this project is to read teacher’s preferences to assign them to study groups in courses.This project is inspired by the link:https://github.com/oliviercailloux/Teach-spreadsheets[Teach-spreadsheets project].

== Global idea of the project 

The main functionalities that this project will implement are described in the link:Doc\README.adoc#UseCaseDiag[use case diagram]. +
The way we imagine the process of assignment is described in the link:Doc\README.adoc#SeqDiag[sequence diagram]. +
The classes that we plan to implement are described in the link:Doc\README.adoc#ClassDiag[class diagram].

== Third java iteration

* Group 1: SM/PO: Inès

** Adding loggins in the code

* Group 2 : Hedi and Mike

** Fixing issues from iteration 1 about base package

** Creation of a class reading a set of input vows files

** GUI for assignment

* Group 3 : Semida and Sarah

** Fixing issue from iteration 2 about assignment package and correcting this package according to the needs of Group 2

** Correcting json package according iteration 2 comments in order to merge it into master

** Reviewing the structure of the classes in the package write (to avoid code duplication), correcting this package according iteration 2 comments in order to merge it into master and adding more fonctionalities to improve the aesthetic of the created files

** Correcting diverse classes of the project : removing warnings, adding a studyLevel attribute in Course class and changing the value of studyYear according to iteration 2 issue

== What was done in the first java iteration  

* Group 1: Mike and Inès 

** Created the skeleton (attributes and getters) of classes Course, Teacher CoursePref and CalcData. 

** Prepared some samples of “AA - Saisie des voeux 2016-2017.ods" as if they were completed by teachers.  

* Group 2:  Hedi and Sarah 

** Created the skeleton (attributes and getters) of the class CourseAssignement and Assignment. 

** Looked for how to read a Calc document. 

** Read the Calc document “AA - Saisie des voeux 2016-2017.ods" and instantiated a CalcData variable. 

* Semida 

** Created a class which summarises the samples of “AA - Saisie des voeux 2016-2017.ods" made by writing teachers' preferences in a Calc. 

== What was done in the second java iteration

* Group 1: SM/PO : Hedi 

** Does the necessary changes in order to merge the branch it1-java-Hedi-Sarah to master

** Looks for a way to read the tabs "LSO", "Apprentissage" and improve the reader classes

** Verifies that the merges are not problematic


* Group 2: Mike and Sarah

** Reads and writes a list of courses in JSON

** Reads a list of teachers from RefRof

** Deals with the comments and issues from iteration 1 for the classes in the packages assignment and base


* Group 3: Semida and Inès

** Does the necessary changes in order to merge the branch it1-Semida to master

** Adds new features to the class OdsSummarizer (examples : export to pdf, make a more design Calc ...)

** Creates new classes in order to write the result of the assignment process into new ods files : AssignmentPerTeacher and GlobalAssigment