= Teach spreadsheets

== About the project

The aim of this project is to read teacher’s preferences to assign them to study groups in courses.This project is inspired by the link:https://github.com/oliviercailloux/Teach-spreadsheets[Teach-spreadsheets project].

*Logos' Credits* :

The Icons used in the gui are made by link:https://www.flaticon.com/authors/freepik[Freepik], link:https://www.flaticon.com/authors/xnimrodx[nimrodx] and link:https://www.flaticon.com/authors/prosymbols[Prosymbols] from link:https://www.flaticon.com/[www.flaticon.com].

== Global idea of the project 

The main functionalities that this project will implement are described in the link:Doc\README.adoc#UseCaseDiag[use case diagram]. +
You can see how our program's gui looks like in link:Doc\README.adoc#GuiDescription[gui description]. +
The way we imagine the process of assignment is described in the link:Doc\README.adoc#SeqDiag[sequence diagram]. +
The packages in our program are modelled in the link:Doc\README.adoc#Package[package diagram]. +
The classes implemented are described in the link:Doc\README.adoc#ClassDiag[class diagram].

== Fourth java iteration

* Group 1: SM/PO: Sarah

** Fixing as many issues as possible : Issues 22, 25, 32, 33 ... 
** Adding teacherAssignmentsToCourseAssignments() in CourseAssignment

* Group 2 : Hedi and Semida

** Fixing issue 34

** Making the project's main 


* Group 3 : Mike and Inès

** Completing the GUI for Assignment

== List of the missions done by each member of the group

* Sarah :

** I coded in almost all the packages of our project (except for gui package). Here is the list of my missions:

*** for assignment package, I:
**** coded TeacherAssignment and CourseAssignment classes

*** for write package, I:
**** corrected setInfoPref() and readSemester() in CourseAndPrefReader and the code of PrefsInitializer
**** documented classes
**** made the unit tests for TeacherReader, readSemester() in CourseAndPrefReader, PrefsInitializer, TeacherPrefsInitializer

*** for json package, I:
**** coded JsonDeserializer and made its unit test +
Comment: It was difficult for me to understand how to use jsonb. Moreover, understanding how to extract teachers’ information from RefRof was very difficult. With some time and practice, I managed to understand both.
**** corrected JsonSerializer to fit PR comments

*** for write package, I:
**** reorganised the code in GlobalAssignment, TeacherPreferences and AssignmentPerTeacher to avoid code duplication.
**** coded the methods to format the documents generated by OdsSummarizer and AssignmentPerTeacher. +
Comment: The formatting of the documents generated was easy. However, it took me a long time to get a very aesthetic result, especially for the table in OdsSummarizer.ods.

*** for base package, I:
**** recoded almost all the unit tests to make sure that the project’s code fails fast as desired.
**** coded AggregatedPrefs.

*** I will also make diverse corrections to different packages of the code to close the opened issues.


* Ines :

** I helped in the code for differents package with each groups
** improved remarks of our teacher
** tried to correct some issues
** documentation (itx.adoc, readme, classes, etc..)
** uml diagram with papyrus
** "cleaned" the folder, and deleted the unless files
** helped for the GUI, coded some methods in the controller

* Semida :

** My main task was the writing package i.e. the following classes : OdsHelper, AssignmentPerTeacher and OdsSummarizer.  I developed on it since the first iteration until the last and with the precious help of my mates, we achieved the final result.   

** I also made my humble contribution on several other classes as for example : classes Course, CourseTests, Teacher and TeacherTests (on branch it3-Equals), CourseAssignment (on branch it3-Assignment), AggregatedData and AggregatedDataTests (on branch it3-AD), Controller (on branch it4-Main) ...

* Hedi :

** I coded the classes in the read package and its unit tests.
** I coded some parts of the gui package (mostly the view and few parts of the controller).
** I wrote the App class in the main package (containg the main of this program).
** I tested with Semida the writing time to disk for 100 assignments.
