= Teach spreadsheets
== Aim of the project 

The aim of this project is to read teacher’s preferences to assign them to study groups in courses.

== Global idea of the project 

The main functionalities that this project will implement are described in the link:Docs\DiagramDocs\README.adoc[use case diagram]. +
The way we imagine the process of assignment is described in the link:anchor:bookmark-a[sequence diagram]. +
The classes that we plan to implement are described in the link:Docs\DiagramDocs\README.adoc[class diagram].

== Second java iteration

* Group 1: SM/PO : Hedi 

** Does the necessary changes in order to merge the branch it1-java-Hedi-Sarah to master

** Looks for a way to read the tabs "LSO" and "Apprentissage"

** Verifies that the merges are not problematic


* Group 2: Mike and Sarah

** Reads and writes a list of courses 

** Does the necessary changes on classes Assignment


* Group 3: Semida and Inès

** Does the necessary changes in order to merge the branch it1-Semida to master

** Adds new features to the class OdsSummarizer (examples : export to pdf, make a more design Calc ...)

== What was done in the first java iteration  

* Group 1: Mike and Inès 

** Created the skeleton (attributes and getters) of classes Course, Teacher CoursePref and CalcData. 

** Prepared some samples of “AA - Saisie des voeux 2016-2017.ods" as if they were completed by teachers. 

** Got courses and teachers with Json API to populate CalcData. 

* Group 2:  Hedi and Sarah 

** Created the skeleton (attributes and getters) of the class CourseAssignement and Assignment. 

** Looked for how to read a Calc document. 

** Read the Calc document “AA - Saisie des voeux 2016-2017.ods" and instantiated a CalcData variable. 

* Semida 

** Created a class which summarises the samples of “AA - Saisie des voeux 2016-2017.ods" made by writing teachers' preferences in a Calc. 