= Iteration 3 UML 

The aim of this iteration is to correct and improve UML Iteration 2 by taking into consideration Mr. Cailloux’s remarks. We also did new Class Diagrams for the classes we implemented in the first java iteration.

Here is the list of the modifications that were made by each one : 

* The group constituted of Hedi GUEDIDI, Semida BUZDUGAN and Inès DRAREDJA divided the corrections as follows: 

** Hedi GUEDIDI : 

*** Creating the Class_ODS_Read diagram and its documentaion
*** Correcting and updating the Class_assignment diagram and its documentation

** Semida BUZDUGAN : 

*** Removed useless files : Model_fr_FR.propreties and .project in the Diagrams folder

*** Improving documents files

** Inès DRAREDJA

*** ...

* The group constituted of Sarah EL HELW and Mike SANTANGELO divided the corrections as follows: 

** Sarah EL HELW
 
*** For the sequence diagrams :
**** Changing the subject and name of the first sequence diagram
**** Changing the name of the third lifeline in the sequence diagrams to match the subject in the use case diagram

*** For the documentation :
**** Ading links to the documents Fichier Agrégé.pdf, AA-Saisie des voeux 2016-2017.od, services MIDO.xls and Fiche de service.png
****  Merging the three documents describing the diagrams into one

** Mike SANTANGELO 

*** ...